var net;if(net){if(typeof net!="object")throw Error("net already exists and is not an object");}else net={};if(net.pretopia){if(typeof net.pretopia!="object")throw Error("net.pretopia already exists and is not an object");}else net.pretopia={};if(net.pretopia.utils)throw Error("net.pretopia.utils already exists");net.pretopia.utils=function(){};net.pretopia.utils.prototype.getLeftXCoordinate=function(a){for(var c=a.offsetLeft;a=a.offsetParent;)c+=a.offsetLeft;return c};
net.pretopia.utils.prototype.getTopYCoordinate=function(a){for(var c=a.offsetTop;a=a.offsetParent;)c+=a.offsetTop;return c};net.pretopia.utils.prototype.getPointer=function(a,c){var f=a.touches!=void 0?a.touches[0]:a;return{isTouch:a.touches!=void 0,x:f.pageX-this.getLeftXCoordinate(c),y:f.pageY-this.getTopYCoordinate(c)}};
net.pretopia.DEVICE=function(){var a={isInitialized:!1,isMobile:!1,isAppMode:!1,device:{family:"",hasRetina:!1},OS:{name:"",version:"",build:""}},c=navigator.userAgent,f=[{regExpr:/iPhone/,device:"iPhone",OS:"iOS"},{regExpr:/iPod/,device:"iPod",OS:"iOS"},{regExpr:/iPad/,device:"iPad",OS:"iOS"},{regExpr:/Android/,device:"",OS:"Android"}];a.isInitialized=function(){for(var g=0;g<f.length;g++)if(c.match(f[g].regExpr)){a.device.family=f[g].device;a.device.hasRetina=window.devicePixelRatio==2;a.OS.name=
f[g].OS;switch(a.OS.name){case "iOS":a.isMobile=!0;a.OS.version=c.match(/OS\s(\S+)/)[1].replace(/_/g,".");break;case "Android":a.isMobile=!0,a.OS.version=c.match(/Android\s(\S+);/)[1],g=c.match(/;((\s([A-Za-z0-9_-]+[^;]))+)(\sBuild\/(\w+))?\)/),a.device.family=g[1].substr(1),a.OS.build=g[5]!=void 0?g[5]:""}break}a.isAppMode=navigator.standalone?navigator.standalone:!1;return!0}();return a}();
net.pretopia.Sketchpad=function(a,c){var f=net.pretopia.DEVICE,g=new net.pretopia.utils,b,d,e,a=document.getElementById(a),h=3,m=function(a){a.preventDefault();e&&(a=g.getPointer(a,b),d.lineTo(a.x,a.y),d.stroke())},k=function(a){var c=g.getPointer(a,b);!e&&a.type=="mousedown"||a.type=="touchstart"?(d.moveTo(c.x,c.y),d.beginPath(),e=!0):(c.isTouch||(a=g.getPointer(a,b),d.strokeRect(a.x,a.y,1,1),d.stroke()),d.closePath(),e=!1)};this.setPointerDiameter=function(a){a=parseInt(a);if(a>0&&a<=20)d.closePath(),
d.lineWidth=a,d.beginPath(),h=a};this.getPointerDiameter=function(){return h};this.setPointerColor=function(a){d.strokeStyle=a};this.getPointerColor=function(){return d.strokeStyle};this.clear=function(){d=b.getContext("2d");d.lineWidth=h;d.lineJoin="round";d.fillStyle="#ffffff";d.fillRect(0,0,b.width,b.height);d.fill();e=!1};this.exportImage=function(a){return b.toDataURL(a||"image/png")};this.init=function(){b=document.createElement("canvas");b.className="sketchpad";a.appendChild(b);b.width=c.width||
320;b.height=c.height||480;this.clear();this.setPointerColor("#000000");f.isMobile?(b.addEventListener("touchstart",k,!1),b.addEventListener("touchmove",m,!1)):(b.addEventListener("mousedown",k,!1),b.addEventListener("mouseup",k,!1),b.addEventListener("mousemove",m,!1))}};
net.pretopia.ColorPicker=function(a,c){var f=net.pretopia.DEVICE,g=new net.pretopia.utils,b="#000000",d,a=document.getElementById(a),e=document.createElement("canvas");e.className="colorpicker";a.appendChild(e);var h=function(a,c){var b=g.getPointer(a,e),f=d.getImageData(b.x,b.y,1,1).data,b=f[0].toString(16),h=f[1].toString(16),f=f[2].toString(16),b="#"+(b.length==2?b:"0"+b)+(h.length==2?h:"0"+h)+(f.length==2?f:"0"+f);c!==void 0&&c(b);return b};this.getPickedColor=function(){return b};this.setParams=
function(a){typeof a==="object"&&(c=a)};this.render=function(){var a,g=0,n=c.lightness!==void 0?c.lightness:50,o=c.showColor||function(){},l=c.chooseColor||function(){};e.width=c.width||360;e.height=c.height||100;d=e.getContext("2d");for(var i=0;i<=e.width;i++){a=100;for(var j=0;j<=e.height;j++)d.fillStyle="hsl("+g+", "+a+"%, "+n+"%)",d.fillRect(i,j,1,1),a=Math.ceil(100-j*(100/e.height));g=Math.ceil(360+i*(360/e.width))}d.fill();f.isMobile?(e.addEventListener("touchstart",function(a){b=h(a,l)},!1),
e.addEventListener("touchmove",function(a){a.preventDefault();b=h(a,l)},!1)):(e.addEventListener("mousemove",function(a){h(a,o)},!1),e.addEventListener("click",function(a){b=h(a,l)},!1))}};