var net;if(!net)net={};else if("object"!=typeof net)throw Error("net already exists and is not an object");if(!net.pretopia)net.pretopia={};else if("object"!=typeof net.pretopia)throw Error("net.pretopia already exists and is not an object");if(net.pretopia.FloodIt)throw Error("net.pretopia.FloodIt already exists");
net.pretopia.FloodIt=function(A){function D(a){for(var c=a.offsetTop;a=a.offsetParent;)c+=a.offsetTop;return c}function E(){for(var a=document.getElementById(l+"_col_0_0").style.backgroundColor,c,b=0;b<g;b++)for(var e=0;e<g;e++)if(c=a,a=document.getElementById(l+"_col_"+e+"_"+b).style.backgroundColor,a!=c)return!1;return!0}function m(a,c){return document.getElementById(l+"_col_"+a+"_"+c).style.backgroundColor}function F(a,c,b){document.getElementById(l+"_col_"+a+"_"+c).style.background=b}function B(a){for(var c,
b,e,d,n=document.getElementById(l+"_FloodItTurns"),f=Array(g),h=0;h<g;h++)f[h]=Array(g);if(!(a==C||0>=w||E())){C=a;for(var h=0,k=q.length;h<k;h++)e=q[h].x,d=q[h].y,F(e,d,r[a]),c=m(e,d),f[e][d]=!0,e<g-1&&(b=m(e+1,d),b!=c||f[e+1][d]||(q[k++]={x:e+1,y:d})),d<g-1&&(b=m(e,d+1),b!=c||f[e][d+1]||(q[k++]={x:e,y:d+1})),0<e&&(b=m(e-1,d),b!=c||f[e-1][d]||(q[k++]={x:e-1,y:d})),0<d&&(b=m(e,d-1),b!=c||f[e][d-1]||(q[k++]={x:e,y:d-1}));w--;x=t-w;w==t?(n.innerHTML="Tap a color to start",u<=t+1&&(n.innerHTML+='<div style="font-size: 14px; color: #78909c;">Personal best: '+
u+" turns</div>")):(n.innerHTML=x+" of "+t+" turns used",u<=t&&(n.innerHTML+='<div style="font-size: 14px; color: #78909c;">Personal best: '+u+" turns</div>"));E()?(x<u?(localStorage["net.pretopia.FloodIt.highScore"]=x,a=document.getElementById("endGamePanel"),a.className="slider",a.style.fontSize="60px",a.innerHTML='<div style="margin-top: 35px; color: #7dff52;">Woohoo!</div>',a.innerHTML+='<div style="margin-top: 15px; font-size: 20px;">You flooded the board in <span style="color: #7dff52;">'+x+
"</span> turns, a new personal best!</div>"):(a=document.getElementById("endGamePanel"),a.className="slider",a.style.fontSize="60px",a.innerHTML='<div style="margin-top: 35px; color: #7dff52;">Hooray!</div>',a.innerHTML+='<div style="margin-top: 15px; font-size: 20px;">You flooded the board in <span style="color: #7dff52;">'+x+"</span> turns</div>",a.innerHTML+='<div style="margin-top: 15px; font-size: 20px;">Try beating your personal best of '+u+"</div>"),c=document.createElement("div"),c.className=
"retryButton",c.innerHTML="Play again",c.addEventListener("click",function(){loadGame()},!1),c.addEventListener("touchstart",function(){loadGame()},!1),a.appendChild(c)):0>=w&&(a=document.getElementById("endGamePanel"),a.className="slider",a.style.fontSize="60px",a.innerHTML='<div style="margin-top: 35px;">Game Over</div>',c=document.createElement("div"),c.className="retryButton",c.innerHTML="Play again",c.addEventListener("click",function(){loadGame()},!1),c.addEventListener("touchstart",function(){loadGame()},
!1),a.appendChild(c))}}function G(){var a="#ff0000",c=-1,b=-1,e=-1,c=Math.floor(p/g),d=p/r.length,n=b=null,f=null,h=null,k=null,a=null;document.getElementById("endGamePanel").className="slider closed";null==(n=document.getElementById(l))&&(n=document.body);u=99999>localStorage["net.pretopia.FloodIt.highScore"]?localStorage["net.pretopia.FloodIt.highScore"]:99999;q=[{x:0,y:0}];C=-1;w=t+1;turnsLeft=t;null!=(f=document.getElementById(l+"_FloodItWrapper"))&&n.removeChild(f);f=document.createElement("div");
f.id=l+"_FloodItWrapper";f.className="FloodItWrapper";n.appendChild(f);k=document.createElement("div");k.id=l+"_FloodItTurns";k.style.fontSize="34px";k.style.position="relative";k.style.color="#37474f";k.style.width=p+"px";k.className="FloodItTurns";h=document.createElement("div");h.className="FloodItBoard";f.appendChild(h);f.appendChild(k);for(var v=0;v<g;v++)for(var m=0;m<g;m++)b=Math.floor(6*Math.random()),a=r[b],0==v&&0==m&&(e=b),b=document.createElement("div"),b.id=l+"_col_"+m+"_"+v,b.style.position=
"relative",b.style.cssFloat="left",b.style.width=c+"px",b.style.height=c+"px",b.style.background=a,h.appendChild(b),m==g-1&&(b=document.createElement("div"),b.style.width="0px",h.appendChild(b));document.getElementById("copyright").style.width=p+"px";document.getElementById("copyright").style.marginLeft=-(p/2)+"px";a=document.createElement("div");a.className="FloodItLegend";a.style.width=p+"px";a.style.marginLeft=-(p/2)+"px";a.id=l+"_legend";f.appendChild(a);for(f=0;f<y[1].length;f++)b=document.createElement("div"),
b.className="FloodItLegendSquare",b.style.background=y[1][f],b.id=l+"_legend_"+f,b.value=f,v=document.createElement("div"),v.innerHTML="&nbsp;",b.appendChild(v),b.style.width=d-5+"px",b.style.height=d-5+"px",5!=f&&(b.style.marginRight="6px"),b.addEventListener("click",function(){B(this.value)},!1),b.addEventListener("touchstart",function(){B(this.value)},!1),a.appendChild(b);d=D(a)-(D(n)+c*g);150<d&&(document.body.style.paddingTop="40px",d-=40);d/=2;c=parseInt(document.getElementById(l+"_col_0_0").offsetHeight);
h.style.width=g*c+"px";k.style.top=d-36+"px";return e}var l=null!=A&&""!=A?A:"FloodItInstance",p=600,g=12,t=22,C=-1,w=-1,x=-1,q=null,u=99999,y=["rgb(206, 86, 49);rgb(135, 150, 52);rgb(90, 102, 164);rgb(222, 127, 161);rgb(248, 236, 78);rgb(91, 179, 222)".split(";"),"rgb(174,73,41) rgb(109,121,42) rgb(76,86,139) rgb(210,80,127) rgb(246,230,21) rgb(49,159,213)".split(" ")],z=0,r=y[z];this.toggleTheme=function(){for(var a=z==y.length-1?0:z+1,c=null,b=0;b<g;b++)for(var e=0;e<g;e++)for(var c=m(b,e),d=0;d<
r.length;d++)if(r[d]==c){F(b,e,y[a][d]);break}r=y[a];z=a;for(a=0;a<r.length;a++)document.getElementById(l+"_legend_"+a).style.background=r[a]};this.main=function(a,c,b){a=parseInt(a);c=parseInt(c);b=parseInt(b);p=540>b?b:540;p-=20;g=null!=a&&1<a&&40>a?a:12;t=null!=c&&0<c&&1E3>c?c:22;a=-1;a=G();B(a)}};